"""Add TermsOfService and PrivacyPolicy models for legal content management

Revision ID: 0ea7e082b082
Revises: 44ba73ad22cb
Create Date: 2025-07-01 11:48:03.091197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea7e082b082'
down_revision = '44ba73ad22cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privacy_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terms_of_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### DISABLED FOR DATA SAFETY ###
    # 데이터 보호를 위해 downgrade 기능을 비활성화합니다.
    pass
    # ### ORIGINAL CODE COMMENTED OUT ###
    # op.drop_table('terms_of_service')
    # op.drop_table('privacy_policy')
