"""Remove carousel functionality

Revision ID: 2f7c83e371b7
Revises: 7d4e40c80aa1
Create Date: 2025-06-30 10:42:38.177043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7c83e371b7'
down_revision = '7d4e40c80aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carousel_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carousel_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=200), nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=200), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
