"""Add display_order and is_pinned to GalleryGroup

Revision ID: 3decf0f6d2e9
Revises: 2f7c83e371b7
Create Date: 2025-06-30 10:47:49.406529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3decf0f6d2e9'
down_revision = '2f7c83e371b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_group', schema=None) as batch_op:
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
