"""Add SiteSettings model for color management

Revision ID: 44ba73ad22cb
Revises: 3decf0f6d2e9
Create Date: 2025-07-01 10:45:32.804983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ba73ad22cb'
down_revision = '3decf0f6d2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_color_r', sa.Integer(), nullable=True),
    sa.Column('main_color_g', sa.Integer(), nullable=True),
    sa.Column('main_color_b', sa.Integer(), nullable=True),
    sa.Column('sub_color_r', sa.Integer(), nullable=True),
    sa.Column('sub_color_g', sa.Integer(), nullable=True),
    sa.Column('sub_color_b', sa.Integer(), nullable=True),
    sa.Column('background_color_r', sa.Integer(), nullable=True),
    sa.Column('background_color_g', sa.Integer(), nullable=True),
    sa.Column('background_color_b', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
