"""add overtime_charge_table to service_option

Revision ID: 6275ee549efc
Revises: 8f16b162a146
Create Date: 2025-07-01 14:38:18.988164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6275ee549efc'
down_revision = '8f16b162a146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overtime_charge_table', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_option', schema=None) as batch_op:
        batch_op.drop_column('overtime_charge_table')

    # ### end Alembic commands ###
