"""add_refund_policy_text_and_table_fields

Revision ID: 8f16b162a146
Revises: fb9619e497a4
Create Date: 2025-07-01 13:49:27.225045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f16b162a146'
down_revision = 'fb9619e497a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refund_policy_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refund_policy_table', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_option', schema=None) as batch_op:
        batch_op.drop_column('refund_policy_table')
        batch_op.drop_column('refund_policy_text')

    # ### end Alembic commands ###
