"""Add subtitle to Gallery model

Revision ID: a7c88d00ceb7
Revises: dcd3d480bf79
Create Date: 2025-02-14 11:51:31.078691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c88d00ceb7'
down_revision = 'dcd3d480bf79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('subtitle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order')
        batch_op.drop_column('group_id')
        batch_op.drop_column('caption')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('order', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'gallery_group', ['group_id'], ['id'])
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('subtitle')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
