"""add_booking_conditions_to_service_option

Revision ID: fb9619e497a4
Revises: 0ea7e082b082
Create Date: 2025-07-01 13:26:36.615035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9619e497a4'
down_revision = '0ea7e082b082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_method', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('guide_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refund_policy', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_option', schema=None) as batch_op:
        batch_op.drop_column('refund_policy')
        batch_op.drop_column('guide_info')
        batch_op.drop_column('payment_info')
        batch_op.drop_column('booking_method')

    # ### end Alembic commands ###
